### ISSUE TITLE
Does the latest 4.14 kernel include backported bcache bug fixes?

### ISSUE THREAD

**Issue by xiaofanshifu** [openela/kernel-lts#10]
Hi, does the latest 4.14 kernel version maintained by OpenELA include backported bug fixes for the bcache module from the latest kernel releases?

**Comment by harshimogalapalli** [comment]
Hi @thissuper ,

Thanks for asking.

$ git log --oneline v4.14.336..v4.14.351-openela drivers/md/bcache/

-- None.

But that is because the source of patches for 4.14.y-openELA is 4.19.y stable branch, if there are fixes in 4.19.y and which are relevant to 4.14.y-openELA, they will be applied.

You can also send backports to 4.14.y from 4.19.y if you think any of them are missing. We will be happy to review and backport.

Thanks,
Harshit
